# docker-compose.yml
version: "3.9"

services:
  db:
    image: postgres:15
    container_name: tanuki_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data"

volumes:
  pgdata:
