name: CI Backend

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Lint (ruff)
        run: poetry run ruff check .

      - name: Type check (mypy)
        run: poetry run mypy .

      - name: Run tests
        run: poetry run pytest --cov=app --cov-report=term-missing --cov-fail-under=80

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
